"""Module for reading the SETTINGS.json file.
"""

import json
import os

with open(os.path.dirname(os.path.realpath(__file__)) + '/SETTINGS.json') as data_file:
    PATHS = json.load(data_file)

TRAIN_DATA_PATH = PATHS["TRAIN_DATA_PATH"]
TEST_DATA_PATH = PATHS["VALIDATE_DATA_PATH"]
PKL_TRAIN_DATA_PATH = PATHS["PKL_TRAIN_DATA_PATH"]
PKL_TEST_DATA_PATH = PATHS["PKL_VALIDATE_DATA_PATH"]
MODEL_PATH = PATHS["MODEL_PATH"]
SUBMISSION_PATH = PATHS["SUBMISSION_PATH"]
LOGS_PATH = PATHS["LOGS_PATH"]
INTERMEDIATE_PREDICTIONS_PATH = PATHS["INTERMEDIATE_PREDICTIONS_PATH"]
TEMP_FILES_PATH = PATHS["TEMP_FILES_PATH"]
TRAIN_PATIENT_IDS = PATHS["TRAIN_PATIENT_IDS"]
TEST_PATIENT_IDS = PATHS["TEST_PATIENT_IDS"]
SUBMISSION_NR = PATHS["SUBMISSION_NR"]
ENSEMBLE_WEIGHTS_PATH = PATHS["ENSEMBLE_WEIGHTS_PATH"]
